const DATA=[{x:100,y:20},{x:150,y:27},{x:200,y:36},{x:250,y:44},{x:300,y:53},{x:350,y:61},{x:400,y:69},{x:450,y:78},{x:500,y:87}];
const NS='http://www.w3.org/2000/svg';
const KEY='ai-learn.progress.v1';
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
function el(tag,a={}){const n=document.createElementNS(NS,tag);Object.entries(a).forEach(([k,v])=>n.setAttribute(k,v));return n}
function geo(){return{sx:x=>58+(x-100)/400*558,sy:y=>24+(1-(y-10)/90)*290}}
function axes(svg){const g=geo();[20,40,60,80,100].forEach(y=>{svg.append(el('line',{x1:58,y1:g.sy(y),x2:616,y2:g.sy(y),class:'grid'}));const t=el('text',{x:46,y:g.sy(y)+4,'text-anchor':'end',class:'label-text'});t.textContent=y;svg.append(t)});[100,200,300,400,500].forEach(x=>{svg.append(el('line',{x1:g.sx(x),y1:24,x2:g.sx(x),y2:314,class:'grid'}));const t=el('text',{x:g.sx(x),y:342,'text-anchor':'middle',class:'label-text'});t.textContent=x;svg.append(t)});svg.append(el('line',{x1:58,y1:314,x2:616,y2:314,class:'axis'}));svg.append(el('line',{x1:58,y1:24,x2:58,y2:314,class:'axis'}))}
function regression(x=350){const svg=$('#regressionChart');if(!svg)return;svg.replaceChildren();axes(svg);const g=geo();const p=el('path',{class:'model-line',d:`M ${g.sx(100)} ${g.sy(19)} L ${g.sx(500)} ${g.sy(87)}`});svg.append(p);DATA.forEach(d=>svg.append(el('circle',{cx:g.sx(d.x),cy:g.sy(d.y),r:4.5,class:'point'})));const y=.17*x+2;svg.append(el('line',{x1:g.sx(x),y1:314,x2:g.sx(x),y2:g.sy(y),stroke:'#67e8c5','stroke-dasharray':'5 6',opacity:'.55'}));svg.append(el('circle',{cx:g.sx(x),cy:g.sy(y),r:7,class:'point active'}))}
function fit(mode='good'){const svg=$('#fitChart');if(!svg)return;svg.replaceChildren();axes(svg);const g=geo();DATA.forEach(d=>svg.append(el('circle',{cx:g.sx(d.x),cy:g.sy(d.y),r:4.5,class:'point'})));let d;if(mode==='underfit')d=`M ${g.sx(100)} ${g.sy(50)} L ${g.sx(500)} ${g.sy(50)}`;else if(mode==='overfit')d=DATA.map((p,i)=>`${i?'L':'M'} ${g.sx(p.x)} ${g.sy(p.y+(i%2?5:-4))}`).join(' ');else d=`M ${g.sx(100)} ${g.sy(18)} L ${g.sx(500)} ${g.sy(88)}`;svg.append(el('path',{class:mode==='overfit'?'model-line alt':'model-line',d}))}
function progress(){try{return JSON.parse(localStorage.getItem(KEY))||{completed:[]}}catch{return{completed:[]}}}
function renderProgress(){const p=progress();p.completed=Array.isArray(p.completed)?p.completed:[];const pct=Math.round(p.completed.length/2*100);$('#progressLabel').textContent=`${pct}%`;$('#progressBar').style.width=`${pct}%`;$$('[data-complete]').forEach(b=>{const done=p.completed.includes(b.dataset.complete);b.classList.toggle('done',done);b.textContent=done?'✓ Module selesai':`✓ Tandai ${b.dataset.complete==='module-1'?'Module 1':'Module 2'} selesai`})}
const slider=$('#loadSlider');if(slider){const update=()=>{const x=+slider.value;$('#loadValue').textContent=x;$('#predictionValue').textContent=(.17*x+2).toFixed(1);regression(x)};slider.addEventListener('input',update);update()}
const FIT={underfit:['Underfit','Model terlalu sederhana. Ia belum menangkap pola utama.','15 kW','16 kW'],good:['Good fit','Model menangkap pola utama tanpa mengejar noise.','4 kW','5 kW'],overfit:['Overfit','Training tampak hebat, tetapi model mengejar noise dan buruk pada data baru.','0.1 kW','25 kW']};
$$('[data-fit]').forEach(b=>b.addEventListener('click',()=>{const m=b.dataset.fit,v=FIT[m];$$('[data-fit]').forEach(x=>x.classList.toggle('active',x===b));$('#fitTitle').textContent=v[0];$('#fitDescription').textContent=v[1];$('#trainError').textContent=v[2];$('#testError').textContent=v[3];fit(m)}));fit();
$$('[data-complete]').forEach(b=>b.addEventListener('click',()=>{const p=progress();p.completed=Array.isArray(p.completed)?p.completed:[];if(!p.completed.includes(b.dataset.complete))p.completed.push(b.dataset.complete);localStorage.setItem(KEY,JSON.stringify(p));renderProgress()}));renderProgress();
$('#quizForm')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),ans={q1:'b',q2:'a',q3:'c'};if(Object.keys(ans).some(k=>!f.get(k))){$('#quizResult').textContent='Jawab semua pertanyaan dulu.';$('#quizResult').className='quiz-result bad';return}const score=Object.entries(ans).filter(([k,v])=>f.get(k)===v).length;$('#quizResult').textContent=score===3?'3/3 — Mantap. Konsep dasarnya sudah kena.':`${score}/3 — Coba baca lagi bagian diagnosis model dan data leakage.`;$('#quizResult').className=`quiz-result ${score===3?'good':'bad'}`});
$$('[data-copy]').forEach(b=>b.addEventListener('click',async()=>{const n=document.getElementById(b.dataset.copy);try{await navigator.clipboard.writeText(n.innerText);b.textContent='Copied';setTimeout(()=>b.textContent='Copy',1000)}catch{b.textContent='Copy gagal'}}));
