import { COURSE_MANIFEST, findModule } from './core/course-manifest.mjs';
import { LEGACY_PROGRESS_KEY, completionPercent, markCompleted, migrateProgressV1, normalizeProgress, readProgress, writeProgress } from './core/progress.mjs';
import { node } from './core/dom.mjs';

function ensureStyles(){if(document.querySelector('link[data-ai-dashboard]'))return;const link=document.createElement('link');link.rel='stylesheet';link.href='./dashboard.css';link.dataset.aiDashboard='true';document.head.append(link)}
function mergeLegacyProgress(storage=localStorage){let current=readProgress(storage);try{const raw=storage.getItem(LEGACY_PROGRESS_KEY);if(raw){const legacy=migrateProgressV1(JSON.parse(raw));for(const moduleId of legacy.completed['level-1']??[])current=markCompleted(current,'level-1',moduleId);writeProgress(current,storage)}}catch{}return normalizeProgress(current)}
function statusText(level){return level.status==='published'?'Published':level.status==='in-progress'?'In progress':'Planned'}
function buildLevelCard(level,progress){const pct=completionPercent(progress,COURSE_MANIFEST,level.id);const published=level.modules.filter(module=>module.published);const first=published[0]??level.modules[0];const card=node('article',{className:`path-level ${level.status}`});const top=node('div',{className:'path-level-top'});top.append(node('span',{className:'path-level-number',text:level.id.replace('level-','L')}),node('span',{className:'path-status',text:statusText(level)}));card.append(top,node('h3',{text:level.title}),node('p',{className:'path-meta',text:`${level.modules.length} modules · ${pct}% complete`}));const track=node('div',{className:'path-track'});track.append(node('span',{attrs:{style:`width:${pct}%`}}));card.append(track);card.append(node('a',{className:`path-action ${first?.published?'':'disabled'}`,text:first?.published?(pct?'Continue level →':'Start level →'):'Coming next',attrs:{href:first?.published?first.href:'#learningPath','aria-disabled':first?.published?'false':'true'}}));return card}
function resolveResume(progress){if(progress.lastVisited){const module=findModule(progress.lastVisited.level,progress.lastVisited.module);if(module?.published)return module}for(const level of COURSE_MANIFEST){const done=new Set(progress.completed[level.id]??[]);const next=level.modules.find(module=>module.published&&!done.has(module.id));if(next)return next}return findModule('level-1','01')}
export function mountDashboard(root=document.querySelector('main')){if(!root||document.getElementById('learningPath'))return null;ensureStyles();const progress=mergeLegacyProgress();const section=node('section',{className:'learning-path',attrs:{id:'learningPath'}});const head=node('div',{className:'learning-path-head'});const copy=node('div');copy.append(node('span',{className:'path-kicker',text:'AI ENGINEER PATH'}),node('h2',{text:'Dari Machine Learning sampai Production AI.'}),node('p',{text:'Satu jalur belajar: intuisi → visual → matematika → kode → sistem produksi.'}));const overall=node('div',{className:'overall-progress',attrs:{id:'overallProgress'}});const overallPct=completionPercent(progress,COURSE_MANIFEST);overall.append(node('strong',{text:`${overallPct}%`}),node('span',{text:'overall path'}));head.append(copy,overall);section.append(head);const resume=resolveResume(progress);const resumeBar=node('div',{className:'resume-bar'});resumeBar.append(node('span',{text:'Resume belajar'}),node('a',{text:`${resume.title} →`,attrs:{href:resume.href}}));section.append(resumeBar);const grid=node('div',{className:'path-grid'});COURSE_MANIFEST.forEach(level=>grid.append(buildLevelCard(level,progress)));section.append(grid);root.prepend(section);return section}
if(typeof document!=='undefined')mountDashboard();
