const round=(v,d=6)=>Number(v.toFixed(d));const dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0);
export function cosineSimilarity(a,b){if(a.length!==b.length)throw new Error('dimension mismatch');const na=Math.sqrt(dot(a,a)),nb=Math.sqrt(dot(b,b));return na&&nb?round(dot(a,b)/(na*nb)):0}
export function rankDocuments(query,documents){return documents.map(doc=>({...doc,score:cosineSimilarity(query,doc.vector)})).sort((a,b)=>b.score-a.score)}
export function validateObject(value,schema){const errors=[];if(!value||typeof value!=='object'||Array.isArray(value))return{ok:false,errors:['expected object']};for(const[field,type]of Object.entries(schema)){if(!(field in value))errors.push(`${field}: missing`);else if(typeof value[field]!==type)errors.push(`${field}: expected ${type}`)}return{ok:errors.length===0,errors}}
export function authorizeTool(tool,allowlist){const allowed=Array.isArray(allowlist)&&allowlist.includes(tool);return{tool,allowed,reason:allowed?'explicitly allowed':'not in allowlist'}}
export function agentStop({step,maxSteps,status}){return status==='done'||status==='blocked'||step>=maxSteps}
export function evaluateBinary(predicted,actual){if(predicted.length!==actual.length)throw new Error('dimension mismatch');let tp=0,fp=0,fn=0,tn=0;for(let i=0;i<predicted.length;i++){if(predicted[i]&&actual[i])tp++;else if(predicted[i]&&!actual[i])fp++;else if(!predicted[i]&&actual[i])fn++;else tn++}const ratio=(a,b)=>b?round(a/b):0;return{tp,fp,fn,tn,precision:ratio(tp,tp+fp),recall:ratio(tp,tp+fn),accuracy:ratio(tp+tn,predicted.length)}}
export function routeModel({risk,complexity}){if(risk>=.7)return{route:'strong+review',reason:'high risk'};if(complexity>=.6)return{route:'strong',reason:'complex task'};return{route:'fast',reason:'low risk and complexity'}}
export function traceRag(queryVector,documents,k=2){const retrieved=rankDocuments(queryVector,documents).slice(0,k);return{queryVector:[...queryVector],retrieved,context:retrieved.map(x=>x.text)}}
